spring:
  datasource:
    url: jdbc:mysql://192.168.1.177:7567/analysis_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: mysql1.177

