server:
  port: 18886
  servlet:
    context-path: /api

spring:
  application:
    name: book-manger
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.caoximu.bookmanger
knife4j:
  enable: true
  setting:
    language: zh_cn

# Google OAuth2 配置
google:
  oauth2:
    client-id: aaaa
    client-secret: aaa
    redirect-uri: http://localhost:80/google-login.html
system:
  signature-key:
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl9egxbiu4UJvIUUIHNm9
      Lt6s1yR0cRampGQDb4c+FGcdImuTzyrecT2CWsqXZQ4ZBIFTlKItGFleJ7qveFkT
      i4Ud76/2INkcrQoUYu47uKeAJAmXjujOgCIh+QpV1lD44zGp6ZAJ6quq9dlNpCV4
      /GQT9hkIYyvpS6SbIS1/lj1wijYkSF9dghghzj4xXPeEE7khRFxr4niFY2UTmKji
      nMNhkfmnpvidaz2UjqKpSeOpPste1+gjnp5CnfXvvLWi669qIrRIjBSk0JAbryq9
      C13IpxV6yrXjxPSXXQQ3ASMl3XA2fiVMunVko2lo+ztqSQU7tyCkB8bVhuhBMGUW
      NwIDAQAB
      -----END PUBLIC KEY-----
    private-key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAl9egxbiu4UJvIUUIHNm9Lt6s1yR0cRampGQDb4c+FGcdImuT
      zyrecT2CWsqXZQ4ZBIFTlKItGFleJ7qveFkTi4Ud76/2INkcrQoUYu47uKeAJAmX
      jujOgCIh+QpV1lD44zGp6ZAJ6quq9dlNpCV4/GQT9hkIYyvpS6SbIS1/lj1wijYk
      SF9dghghzj4xXPeEE7khRFxr4niFY2UTmKjinMNhkfmnpvidaz2UjqKpSeOpPste
      1+gjnp5CnfXvvLWi669qIrRIjBSk0JAbryq9C13IpxV6yrXjxPSXXQQ3ASMl3XA2
      fiVMunVko2lo+ztqSQU7tyCkB8bVhuhBMGUWNwIDAQABAoIBAAYqG5LWDp4tOPRx
      fa9+Ki9kRuwXxMpv5aVi52jNus16lN+Nh9tZ8tycvKq8SC0yx1KRgDfWkFzJXrM0
      4bl8aaNjwiALABkRTMK8WAY0LySDWFvI2pL+DJ7TGUH9E223V9i8GW6BXzBcdn0I
      rMhEj9w0oULVKAFZX7KnJM0nWw4EXIJ5x8Vg5+IjtSvGW+HERhyFSqQfwu8L0PeG
      +mgzqwxVdaQ1DDcd6l/zb+mO6xV6RQfGVhnxY6gCLEIFPJZPqZagOMTpfUFdsBdw
      qMt5UKIXVLh/ohodTl9lGvI25BwP8TPoV9cwNDdl4QLKOidsMnX3NuzBXTdAgMAo
      w6jYaBECgYEAu25YILSFxJVcw5hDGfcb8W0zbWAfl1T9UrZhd6tA2LjeT6A/2RBX
      GxIgsV5G2QbRb9Ms4dsnp2b4Cey9uOV/7uAcxFp0qrbjuTCSNzrn9FLfU0vtN2Q+
      LfFaS3/me2sZjsMuhMhalDukhEMjwyr8+fJ8fJg8RySMBlQ1FNRaZEsCgYEAz2RC
      HpldjJKVltYAgzZgPCvvjq4PopIXc8gGLmI0uy9YBOQPl2iQC/NVedUQxFtxr7LA
      fyQvflP0ESknagHXfCXTfdbppaPm0l8yqRuaVK01QXrPfm/0KuL7w01Bjun/VW7o
      G9mUgwmNCV0zyfXc4vLBv9RDryAhNy0qf8jjakUCgYAHIfXcmMIWbxCuqNa04ECB
      +YPhf6z0F1nkkeg3o56+IJrlMNX9LrAB6biwx0Ou8qF5vfGRTsO9jR+XURkPNjye
      HI07s62I6ZjU7VJDI8y78YNqKhOG7hunp+2lveJJhBPe6PKWPwGjbnmeRufPf41M
      /btbCngQxQVHIGE8v7AI7QKBgQCDfo0Ru6n95D8miP+AMmzoGe9lJuXQ7RIjnhKV
      PD005frH9xYPqQOUIC/09GwSI+y8OvkkY/wc+/wHGXHdG9fV5mHnKumv1XEXt7Z2
      VIMQ51WZ89U11KQawRpiJUzI4YK8V3qhld49C0Q6SLb6eYIY/1RrXZmgox2MT33f
      0a6nhQKBgBYiXhzNoZoYe4bkjlGLM5S2SczfHpCwaW1ZhDJPtXuKbUT690fe2YBy
      NUKkuDoBLvFEd9EmxFmHoHnpVaGyYDADiF5vaB0s5TAPAqaYCbnBSjP9pY/oS0wy
      j6y4qbjNloDgd07dkJt/J6LGCmjDLiSwh8vdhftC+pCE/0COhcDd
      -----END RSA PRIVATE KEY-----
security:
  # 排除路径
  excludes:
    # 静态资源
    - /*.html
    - /**/*.html
    - /**/*.css
    - /**/*.js
    # 公共路径
    - /favicon.ico
    - /error
    # swagger 文档配置
    - /*/api-docs
    - /*/api-docs/**
    # actuator 监控配置
    - /actuator
    - /actuator/**
    - /api/auth/login
    - /auth/register
    - /auth/google/login

# 全局限流配置
rate-limit:
  # 是否启用限流
  enabled: true
  # 每秒允许的请求数量
  permits-per-second: 0.5
  # 获取令牌的超时时间（毫秒）
  timeout-millis: 500
  # 限流失败时的错误码
  error-code: 429
  # 限流失败时的错误消息
  error-message: "请求过于频繁，请稍后再试"
  # 排除限流的路径
  excludes:
    # 静态资源
    - /*.html
    - /**/*.html
    - /**/*.css
    - /**/*.js
    - /favicon.ico
    - /error
    # swagger 文档
    - /*/api-docs
    - /*/api-docs/**
    - /swagger-ui.html
    - /swagger-ui/**
    - /webjars/**
    - /api/v2/api-docs
    - /api/swagger-resources
    # actuator 监控
    - /actuator
    - /actuator/**
    # 健康检查
    - /health
    - /ping
# Sa-Token配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录，为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token，为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: false

logging:
  level:
    root: info