spring:
  datasource:
    url: jdbc:mysql://120.79.250.74:17567/book_manger?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: mysql1.177

